/// Flutter icons Iconswhapp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iconswhapp
///      fonts:
///       - asset: fonts/Iconswhapp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Iconswhapp {
  Iconswhapp._();

  static const _kFontFam = 'Iconswhapp';
  static const _kFontPkg = null;

  static const IconData circle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_alt = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_download = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_alt = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
